### ISSUE TITLE
Revision Suggestions for Notes-Compilation

### ISSUE THREAD

**Issue by timothy** [czifro-tech/mudt#20]
I have revision suggestions for Notes-Compilation.

I added comments to this pdf and some simple suggestions [Notes-Compilation.pdf](https://github.com/czifro-tech/mudt/files/709361/Notes-Compilation.pdf)

Here is the mark down revision suggestion for [Notes-Compilation.md.txt](https://github.com/czifro-tech/mudt/files/709384/Notes-Compilation.md.txt)

Hope this helps!

**Comment by czifro** [comment]
Just to make it so Tim's suggestions can be viewed here without downloading, here they are:

1. On line 6 of github view, fix "non CPU" => "non-CPU"
2. On line 13 of github view, "through the use of" => "using"
3. On line 16 of github view, "Syme et al." format is in question.
4. In file io section, line 7, "whats" should be "what's"
5. In file io section. 3 par, line 3, "end" should be "and"
6. In file io section. 3 par, line 8, "In order to be cross platform" => "To be cross platform"
7. In file io section. 4 par, line 4, "vary" should be "very"

**Comment by czifro** [comment]
Another review by Ryan Babcock:

>p.2 blocks act like "sub-partitions"? Elaborate. | Consider using tables instead of text for test data | No need to mention "early implementations of block hashing | Don't use words like "disappointing", stay objective (p.4) | Use 'checksum' rather than 'checksumming' | Give a BROAD overview (1-2 paragraphs) about why each part is important -- checksum, File IO, asynchronous, as an intro. Even if this will mentioned somewhere else, you can repeat/remind the reader of what you are doing.
>To elaborate on the last one mentioned, follow the same structure as an english essay. Use an intro to tell the reader what you'll be talking about and why, so he/she can follow along and understand why he/she is reading a section

**Comment by czifro** [comment]
These points will be addressed in the near future.
